Fix ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -31,10 +31,12 @@ jobs:
             git config --local user.name lbonaldo
             git config --local user.email "bonaldo.luca12@gmail.com"
             git checkout -b ${GITHUB_REF#refs/heads/}-testlogs
-            if [[ $(git fetch origin ${GITHUB_REF#refs/heads/}-testlogs) ]]; then # if a branch exists, fetch it
+            git ls-remote --exit-code --heads origin ${GITHUB_REF#refs/heads/}-testlogs
+            if [ "$?" == "2" ] ; then   # exit code 2 if the branch doesn't exist
+              echo "Branch doesn't exist. Skip fetching";
+            else    # if a branch exists, fetch it
+              git fetch origin ${GITHUB_REF#refs/heads/}-testlogs
               git cherry-pick $(git log -n 1 origin/${GITHUB_REF#refs/heads/}-testlogs --pretty=format:"%H")
-            else
-              echo "Skip fetching"
             fi
           fi
       - uses: julia-actions/setup-julia@v1
